### ISSUE TITLE
Store the DOI Service Terms & Conditions in Github

### ISSUE THREAD

**Issue by mjbuys** [datacite/homepage#104]
Please store the DOI Service Terms & Conditions in Github so that we can assign a DOI and link to this from the member application process.
[DirectMembershipTerms_20200807.pdf](https://github.com/datacite/homepage/files/5176329/DirectMembershipTerms_20200807.pdf)
[ConsortiumMembershipTerms_20200807pdf.pdf](https://github.com/datacite/homepage/files/5176330/ConsortiumMembershipTerms_20200807pdf.pdf)

**Comment by mfenner** [comment]
PDF documents are now publicly available at

* https://datacite.org/documents/ConsortiumMembershipTerms_20200807.pdf
* https://datacite.org/documents/DirectMembershipTerms_20200807.pdf
