### ISSUE TITLE
New logo for SND

### ISSUE THREAD

**Issue by borsna** [datacite/homepage#18]
Could not find the asset in this repo for https://assets.datacite.org/images/members/snd.png
Our new logo is available in svg at: https://snd.gu.se/themes/snd/logo--en.svg

**Comment by mfenner** [comment]
The new logo is now available at https://doi.datacite.org/providers/snd and https://www.datacite.org/members.html.

Converted logo to png and cropped at 500px x 200px to be consistent with other logos. Will support svg logos in the future.
