### ISSUE TITLE
Update link under "Learn More" on content negotiation homepage

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/homepage#22]
Link on Content Negotiation page is broken

To reproduce

Navigate to https://datacite.org/content.html
Click on link under "Learn More" > http://crosscite.org/cn/
User receives: Cannot GET /cn/ 

Expected
Correct link is https://citation.crosscite.org/

![image](https://user-images.githubusercontent.com/44582654/54114354-84be8f00-43ea-11e9-8dac-ca195a9e4b3f.png)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_huvv)

**Comment by mfenner** [comment]
Tracked via #21.

**Comment by MaryHirsch** [comment]
Fix as part of #21.
