### ISSUE TITLE
Regroup board page under governance

### ISSUE THREAD

**Issue by mfenner** [datacite/homepage#30]
- [x] Update the board page to include text about the board's role and the roles of the board members. 
  - Update board listing to include new board members. 
  - Update board listing to include each member's term of office. 
  - Links at the bottom of the Governance page will point users to other resources that will NOT get their own listing in the site navigation. These are: 
     - statutes (see homepage#28)
     - strategic plan (Add PDF to homepage repo and link to the file)
     - annual reports for 2018 and 2017 (Add PDFs to homepage repo and link to files)
- [x] ~Update board member photos to be all the same size.~ No longer necessary. See comments.
- [x] Move board page into new section About Us > Governance.

https://docs.google.com/document/d/1chTu9W4uSCfcQjI7FJrPg1BW0srZ5-hMAiQ9j3hh4WE/edit

**Comment by kjgarza** [comment]
![image](https://user-images.githubusercontent.com/1092861/56289688-ce08a980-6121-11e9-882d-4f5926dca948.png)

**Comment by daslerr** [comment]
We looked at making all the board photos the exact same dimensions, but it involved some awkward cropping. We opted instead to make the height of all the photos the same and not worry about widths that are too narrow.

**Comment by mfenner** [comment]
@kjgarza There are some minor cosmetic issues:

![Bildschirmfoto 2019-04-18 um 22.33.16.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/98398e9b-ac99-41d4-bc99-3d1707228544)

![Bildschirmfoto 2019-04-18 um 22.32.38.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/9bda4f3e-650f-4373-9260-a71d2cf100b0)

Also, Adrian Burton works for the Australian Research Data **Commons**.

**Comment by mfenner** [comment]
Please delete `/board.html` and implement a redirect.

**Comment by mfenner** [comment]
Closing in favor of #32.
