### ISSUE TITLE
Update text of What We Do page

### ISSUE THREAD

**Issue by daslerr** [datacite/homepage#31]
Under About Us, update the What We Do page (/mission.html) with the text in this google doc:
https://docs.google.com/document/d/12ghqPeFb54_14LaV-j1e2fT19uYNDH5mIPp4bmgtDNA

**Comment by kjgarza** [comment]
fix https://github.com/datacite/homepage/commit/8ab390aec67f73f2005948cf9ddc7bbaae965af4
