### ISSUE TITLE
Edits for Governance page

### ISSUE THREAD

**Issue by daslerr** [datacite/homepage#32]
- [x] Remove "board applications" section.
- [x] Change title of "board members" section to "Executive Board Members"
- [x] Remove Mike Frame from board list. 
- [x] Order of board members should be Chodacki first (as president), then all others in alphabetical order. 
- [x] Link under "strategic plan" is not aligned on the left with the other text on the page.

**Comment by kjgarza** [comment]
ready for review @daslerr

**Comment by daslerr** [comment]
Last few things: 
- [ ] Add this text at the beginning of the strategic plan section: "Every three years, DataCite approves a new strategic plan for achieving our mission. The latest strategic plan is below."
- [ ] Add this text at the beginning of the annual reports section: "DataCite prepares an annual report in advance of our annual General Assembly meeting that describes our activities for the past year. "
- [ ] Add this text at the beginning of the statutes section, and then link to the existing statutes page (/statutes.html) rather than copying the information: "DataCite prepares an annual report in advance of our annual General Assembly meeting that describes our activities for the past year."
