### ISSUE TITLE
Link from main page broken (crosscite.org)

### ISSUE THREAD

**Issue by HeidiSeibold** [datacite/homepage#88]
When I go to https://datacite.org/ and click on the following

![image](https://user-images.githubusercontent.com/14146757/73536311-eda95e00-4425-11ea-92a2-2fd895982f45.png)

I get to

![image](https://user-images.githubusercontent.com/14146757/73536356-01ed5b00-4426-11ea-94bd-d2066a6ecab3.png)

The page juts says "ok". This is a bit unexpected ;)

**Comment by mfenner** [comment]
This has been fixed, and now correctly points to https://citation.crosscite.org.
